// Writes src/ff20-potential-traits.ts from FIRE Fantasy 20's personality trait table: every trait
// that adds or removes potential, with its odds, length and requirements.
//   npx tsx tools/gen-potential-traits.ts [<Databases dir>]
// The default is the game's staging mod (MM_Data/Modding/Databases), where FF20 is installed.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { gameDataDir } from "../src/regulations.ts";

const dir = process.argv[2] ?? join(gameDataDir(), "Modding", "Databases");
const text = readFileSync(join(dir, "Personality Traits.txt"), "utf8").replace(/^﻿/, "");

/** RFC 4180-ish CSV, as MM's database files are written. */
function parseCsv(s: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [], cell = "", quoted = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (quoted) {
      if (c === '"' && s[i + 1] === '"') { cell += '"'; i++; } else if (c === '"') quoted = false; else cell += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { row.push(cell); cell = ""; } else if (c === "\n") { row.push(cell.replace(/\r$/, "")); rows.push(row); row = []; cell = ""; } else cell += c;
  }
  if (cell || row.length) { row.push(cell); rows.push(row); }
  return rows;
}

const [header, ...rows] = parseCsv(text);
const col = (r: string[], name: string) => (r[header.indexOf(name)] ?? "").trim();

const out = rows.filter((r) => Number(col(r, "Potential"))).map((r) => {
  const req: Record<string, unknown> = {};
  const other: string[] = [];
  for (const clause of col(r, "Requirement").split(";").map((x) => x.trim()).filter(Boolean)) {
    const m = /^(\w+)\s*(<=|>=|=|<|>)\s*(.+)$/.exec(clause);
    if (!m) { other.push(clause); continue; }
    const [, key, op, value] = m;
    if (key === "Age" && op === ">") req.ageAbove = Number(value);
    else if (key === "Age" && op === "<") req.ageBelow = Number(value);
    else if (key === "Potential" && op === "<") req.potentialBelow = Number(value);
    else if (key === "Trait" && op === "=") req.traits = value.split("||").map(Number);
    else if (key === "Employed" && op === "=") req.employed = value === "True";
    else if ((key === "Tier" || key === "TierGT" || key === "TierEndurance") && op === "=") req[key === "Tier" ? "tier" : key === "TierGT" ? "tierGT" : "tierEndurance"] = Number(value);
    else other.push(clause);
  }
  if (other.length) req.other = other;
  const length = col(r, "Length").split("-").map(Number).filter((n) => !Number.isNaN(n));
  return {
    id: Number(col(r, "ID")),
    name: col(r, "Custom Trait Name") || col(r, "Trait Name"),
    potential: Number(col(r, "Potential")),
    chance: Number(col(r, "Probability")) / 100,
    permanent: col(r, "Type") === "Permanent",
    weeks: length.length ? length : null,
    req,
  };
});

const file = `// Generated by tools/gen-potential-traits.ts from FIRE Fantasy 20's "Personality Traits.txt": every
// trait that adds or removes potential. Do not edit by hand.
import type { PotentialTrait } from "./development.ts";

export const FF20_POTENTIAL_TRAITS: PotentialTrait[] = ${JSON.stringify(out, null, 1).replace(/\n\s*/g, " ")};
`.replace(/\[ \{/, "[\n  {").replace(/\}, \{/g, "},\n  {").replace(/\} \];/, "},\n];");
writeFileSync(join(import.meta.dirname, "..", "src", "ff20-potential-traits.ts"), file);
console.log(`wrote ${out.length} traits`);
